// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlVa5SezslFZyO6quJTSPkdSEih-U4u2Q',
    appId: '1:816619792618:web:ea89daf2b3cee3fe674f93',
    messagingSenderId: '816619792618',
    projectId: 'flutterr-7e874',
    authDomain: 'flutterr-7e874.firebaseapp.com',
    storageBucket: 'flutterr-7e874.firebasestorage.app',
    measurementId: 'G-DG4KK4QNN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDearBKqmWzfQJz6D9BztJC_A2xl1C7mWA',
    appId: '1:816619792618:android:f65650702ff75daf674f93',
    messagingSenderId: '816619792618',
    projectId: 'flutterr-7e874',
    storageBucket: 'flutterr-7e874.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQAffEL1X9yRDBveUFUBtVTL4lcCXHioA',
    appId: '1:816619792618:ios:6f80f7fba499c8ae674f93',
    messagingSenderId: '816619792618',
    projectId: 'flutterr-7e874',
    storageBucket: 'flutterr-7e874.firebasestorage.app',
    androidClientId: '816619792618-rrjmlq6r29ipfoqt60o1v4julos8lipd.apps.googleusercontent.com',
    iosClientId: '816619792618-omgkjor0bfunom7b9bpls19p2gi1k4v9.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluterr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQAffEL1X9yRDBveUFUBtVTL4lcCXHioA',
    appId: '1:816619792618:ios:6f80f7fba499c8ae674f93',
    messagingSenderId: '816619792618',
    projectId: 'flutterr-7e874',
    storageBucket: 'flutterr-7e874.firebasestorage.app',
    androidClientId: '816619792618-rrjmlq6r29ipfoqt60o1v4julos8lipd.apps.googleusercontent.com',
    iosClientId: '816619792618-omgkjor0bfunom7b9bpls19p2gi1k4v9.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluterr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlVa5SezslFZyO6quJTSPkdSEih-U4u2Q',
    appId: '1:816619792618:web:040094a3a795ba28674f93',
    messagingSenderId: '816619792618',
    projectId: 'flutterr-7e874',
    authDomain: 'flutterr-7e874.firebaseapp.com',
    storageBucket: 'flutterr-7e874.firebasestorage.app',
    measurementId: 'G-F3E7107M0G',
  );

}